### ISSUE TITLE
GPUBUSY error message

### ISSUE THREAD

**Issue by Scherholz** [DStrelak/atopvis#5]
Hi I keep getting the following error:

root@V32212290358 atopvis [master]$ python3 main.py -atop filenameMonitorStats -to_pickle ./testPickle
INFO:root:Detected 6 cores (including virtual cores)
INFO:root:Detected 3707 MB of memory
INFO:root:Detected 1023 MB of swap
Traceback (most recent call last):
  File "main.py", line 48, in <module>
    main(parse_args())
  File "main.py", line 21, in main
    report = load_report(args)
  File "main.py", line 11, in load_report
    report = AtopReport(atop_file)
  File "/root/atopvis/atop_report.py", line 17, in __init__
    self.resources.extend(AtopsarParser.parse_gpus(file))
  File "/root/atopvis/atopsar_parser.py", line 148, in parse_gpus
    df[c] = pd.to_numeric(df[c].str.replace('%', ''))
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/range.py", line 349, in get_loc
    raise KeyError(key)
KeyError: 'gpubusy'

would appreciate it if you could take a look. 

my environment:

root@V32212290358 atopvis [master]$ uname -a
Linux V32212290358 4.9.241 #2 SMP PREEMPT Tue Apr 25 16:17:03 CST 2023 aarch64 aarch64 aarch64 GNU/Linux

root@V32212290358 atopvis [master]$ python3 --version
Python 3.8.10

root@V32212290358 atopvis [master]$ atop -V
Version: 2.4.0 - 2019/01/12 20:37:57     <gerlof.langeveld@atoptool.nl>

**Comment by DStrelak** [comment]
Hi @Scherholz, 
I fixed some parsing issues.
Please let me know whether your problem still persist.
Thanks!
